/**
 * GamePanel bootstrap 依赖（读档 / 新局启动）。
 * @param {Record<string, unknown>} d
 */
export function buildGamePanelBootstrapDeps(d) {
  return {
    setSuppressShopEnterVisitInit: d.setSuppressShopEnterVisitInit,
    hydrateFromPayload: d.hydrateFromPayload,
    syncOwnedTreasureSlots: d.syncOwnedTreasureSlots,
    syncShopUpgradesFreeFromOwnedTreasures: d.syncShopUpgradesFreeFromOwnedTreasures,
    syncPlayerMarkBatchCounterFromGrid: d.syncPlayerMarkBatchCounterFromGrid,
    getTreasureRunState: d.getTreasureRunState,
    rollRandomBigramForTreasure: d.rollRandomBigramForTreasure,
    registerMaskBubbleDevConsoleHook: d.registerMaskBubbleDevConsoleHook,
    setSlotRafLastTime: d.setSlotRafLastTime,
    ensureSlotRafRunning: d.ensureSlotRafRunning,
    nextTick: d.nextTick,
    setGridIntroDone: d.setGridIntroDone,
    setGridRefillAnimating: d.setGridRefillAnimating,
    getGridCellCount: d.getGridCellCount,
    getGridTileEl: d.getGridTileEl,
    updateSlotPositions: d.updateSlotPositions,
    getShowShop: d.getShowShop,
    shopVisitStockMissingFromSave: d.shopVisitStockMissingFromSave,
    refreshShopVoucherShelfForCurrentVisit: d.refreshShopVoucherShelfForCurrentVisit,
    applyShopVisitStockRoll: d.applyShopVisitStockRoll,
    scheduleRunAutoSave: d.scheduleRunAutoSave,
    flushAchievementUnlocks: d.flushAchievementUnlocks,
    setRunPresetId: d.setRunPresetId,
    getRunPresetIdProp: d.getRunPresetIdProp,
    setRunDifficultyIndex: d.setRunDifficultyIndex,
    getRunDifficultyIndexForNewRun: d.getRunDifficultyIndexForNewRun,
    getRunDifficultyIndexProp: d.getRunDifficultyIndexProp,
    applyRunPresetStartEffects: d.applyRunPresetStartEffects,
    isMaskBubbleDevScenarioActive: d.isMaskBubbleDevScenarioActive,
    applyMaskBubbleOwnedTreasures: d.applyMaskBubbleOwnedTreasures,
    isPagerDevScenarioActive: d.isPagerDevScenarioActive,
    applyPagerOwnedTreasure: d.applyPagerOwnedTreasure,
    isEctoplasmDevScenarioActive: d.isEctoplasmDevScenarioActive,
    applyEctoplasmDevOwnedTreasures: d.applyEctoplasmDevOwnedTreasures,
    isMouthQuProblemDevScenarioActive: d.isMouthQuProblemDevScenarioActive,
    applyMouthQuProblemOwnedTreasures: d.applyMouthQuProblemOwnedTreasures,
    isCeruleanBellDevScenarioActive: d.isCeruleanBellDevScenarioActive,
    applyCeruleanBellDevRunStart: d.applyCeruleanBellDevRunStart,
    isNoSellGoldBombCometDevScenarioActive: d.isNoSellGoldBombCometDevScenarioActive,
    applyNoSellGoldBombCometOwnedTreasures: d.applyNoSellGoldBombCometOwnedTreasures,
    getGamePanelAlive: d.getGamePanelAlive,
    getLevelIndex: d.getLevelIndex,
    resetLevelAfterTreasurePrep: d.resetLevelAfterTreasurePrep,
    runNewRunGridIntro: d.runNewRunGridIntro,
    tryCeruleanBellFlyInAfterGridStable: d.tryCeruleanBellFlyInAfterGridStable,
    syncEndlessLeaderboardChapterBaseline: d.syncEndlessLeaderboardChapterBaseline,
  };
}
