/**
 * 从 GamePanel 分组 ctx 收集 assembly 8 域 sections（替代 GP 手写 flat shorthand）。
 *
 * @param {{
 *   gp: Record<string, unknown>,
 *   ctrls: Record<string, unknown>,
 *   game: Record<string, unknown>,
 *   playfield: Record<string, unknown>,
 *   shop: Record<string, unknown>,
 *   treasure: Record<string, unknown>,
 *   run: Record<string, unknown>,
 *   overlay: Record<string, unknown>,
 *   scoring: Record<string, unknown>,
 *   fx: Record<string, unknown>,
 * }} ctx
 */
export function collectGamePanelAssemblySections(ctx) {
  const { gp, ctrls, game, playfield, shop, treasure, run, overlay, scoring, fx } = ctx;

  return {
    core: {
      COLS: gp.COLS,
      ROWS: gp.ROWS,
      SHOW_SUBMIT_TRANSLATION: gp.SHOW_SUBMIT_TRANSLATION,
      props: gp.props,
      emit: gp.emit,
      session: gp.session,
      phaseStore: gp.phaseStore,
      getGamePanelAlive: gp.getGamePanelAlive,
      mountGamePanelSessionNamespaces: gp.mountGamePanelSessionNamespaces,
      firstWordTutorialCtrlSlot: gp.firstWordTutorialCtrlSlot,
      overlayStackController: ctrls.overlayStackController,
    },
    ctrls: {
      shopPhase: ctrls.shopPhase,
      treasureInventoryCtrl: ctrls.treasureInventoryCtrl,
      tileDetailCtrl: ctrls.tileDetailCtrl,
      runResultPresentationCtrl: ctrls.runResultPresentationCtrl,
      bossMechanicsCtrl: ctrls.bossMechanicsCtrl,
      wordDefinitionCtrl: ctrls.wordDefinitionCtrl,
      shopTransactionCtrl: ctrls.shopTransactionCtrl,
      runLifecycle: ctrls.runLifecycle,
      gpWordSlotPresentation: ctrls.gpWordSlotPresentation,
    },
    grid: {
      grid: game.grid,
      gridIntroDone: game.gridIntroDone,
      gridRefillAnimating: game.gridRefillAnimating,
      gridTileRefs: game.gridTileRefs,
      selectedOrder: game.selectedOrder,
      selectedTiles: game.selectedTiles,
      selectTile: game.selectTile,
      removeFromSlot: game.removeFromSlot,
      removeSingleTileFromWord: game.removeSingleTileFromWord,
      insertSelectedTileAt: game.insertSelectedTileAt,
      reorderSelectedOrder: game.reorderSelectedOrder,
      removeSelectedLetters: game.removeSelectedLetters,
      touchGrid: game.touchGrid,
      releaseManacleBossTopRow: game.releaseManacleBossTopRow,
      flatGrid: playfield.flatGrid,
      snapshotGridCellsByTileId: game.snapshotGridCellsByTileId,
      syncPlayerMarkBatchCounterFromGrid: game.syncPlayerMarkBatchCounterFromGrid,
      ensureSlotRafRunning: playfield.ensureSlotRafRunning,
      updateSlotPositions: playfield.updateSlotPositions,
      letterGridRef: playfield.letterGridRef,
      letterGridWrapRef: playfield.letterGridWrapRef,
      wordSlotRefs: playfield.wordSlotRefs,
      wordSlotsWrapRef: playfield.wordSlotsWrapRef,
      wordSlotsScaleRootRef: playfield.wordSlotsScaleRootRef,
      submitBtnRef: playfield.submitBtnRef,
      submitBookmarkRef: playfield.submitBookmarkRef,
      getGridTileElByIndex: playfield.getGridTileElByIndex,
      getSelectedGridCellElsInOrder: playfield.getSelectedGridCellElsInOrder,
      ceruleanBellSlotIndex: game.ceruleanBellSlotIndex,
      finalizeCeruleanBellSlotIndex: game.finalizeCeruleanBellSlotIndex,
      ensureCeruleanBellMarkedOnGrid: game.ensureCeruleanBellMarkedOnGrid,
      findCeruleanBellLockedTileOnGrid: game.findCeruleanBellLockedTileOnGrid,
      markTileAsWildcard: game.markTileAsWildcard,
      remapTileFromRawLetter: game.remapTileFromRawLetter,
      refreshGridTileBaseScoresFromLevels: game.refreshGridTileBaseScoresFromLevels,
      refreshBossTileDebuffOnTile: game.refreshBossTileDebuffOnTile,
      isManacleBossGrid: game.isManacleBossGrid,
      wordSelectionSwapBusy: playfield.wordSelectionSwapBusy,
      flyingLetters: playfield.flyingLetters,
      flyingBackBatches: playfield.flyingBackBatches,
      deck: game.deck,
      deckBtnRef: playfield.deckBtnRef,
      deckCount: game.deckCount,
      deckPreview: playfield.deckPreview,
      exportDeckState: game.exportDeckState,
      hydrateDeckState: game.hydrateDeckState,
      initialDeckSnapshot: game.initialDeckSnapshot,
      removeDeckCardByUid: game.removeDeckCardByUid,
      removeDeckCardByUidAndNotify: game.removeDeckCardByUidAndNotify,
      removeDeckCardsForSubmittedWord: game.removeDeckCardsForSubmittedWord,
      removeDeckCardsForSubmittedWordAndNotify: game.removeDeckCardsForSubmittedWordAndNotify,
      removeDeckLetterInstancesByRaws: game.removeDeckLetterInstancesByRaws,
      removeDeckLettersByRawsWithTreasureNotify: game.removeDeckLettersByRawsWithTreasureNotify,
      appendShopDeckEntries: game.appendShopDeckEntries,
      appendShopDeckEntriesAndNotify: treasure.appendShopDeckEntriesAndNotify,
      getInRunDeckFlyTargetEl: playfield.getInRunDeckFlyTargetEl,
      remainingRemovals: game.remainingRemovals,
      remainingWords: game.remainingWords,
      basketballWordsSubmitted: game.basketballWordsSubmitted,
      dictFatalError: game.dictFatalError,
      dictionaryReady: game.dictionaryReady,
    },
    shop: {
      showShop: shop.showShop,
      shopPanelRef: shop.shopPanelRef,
      shopPortalZ: shop.shopPortalZ,
      shopPortalStackStyle: shop.shopPortalStackStyle,
      shopOverlayLayersSuppressed: shop.shopOverlayLayersSuppressed,
      shopInteractionsDisabled: shop.shopInteractionsDisabled,
      shopSelectionBridge: shop.shopSelectionBridge,
      shopSpellRuntimeBridge: shop.shopSpellRuntimeBridge,
      onShopNextLevel: run.onShopNextLevel,
      notifyShopLeave: treasure.notifyShopLeave,
      openShopPackSession: shop.openShopPackSession,
      buildShopOwnedPreviewNavItems: treasure.buildShopOwnedPreviewNavItems,
      canPlaceTreasureOffer: treasure.canPlaceTreasureOffer,
      runInRunUpgradePlaybackSteps: shop.runInRunUpgradePlaybackSteps,
      buildInRunLengthUpgradeStep: shop.buildInRunLengthUpgradeStep,
      fulfillPackInnerPurchase: shop.fulfillPackInnerPurchase,
      packPickSession: shop.packPickSession,
      packPickBusy: shop.packPickBusy,
      packPickSkipBusy: shop.packPickSkipBusy,
      packPickOverlaySuppressed: shop.packPickOverlaySuppressed,
      packPickOptionKeyOf: shop.packPickOptionKeyOf,
      packPickRequiredPicks: shop.packPickRequiredPicks,
      runInRunPackPickFlow: shop.runInRunPackPickFlow,
      onPackInnerClaim: shop.onPackInnerClaim,
      onPackPickSkip: shop.onPackPickSkip,
      ensurePackPickOverlayVisible: shop.ensurePackPickOverlayVisible,
      shouldRestorePackPickOverlayAfterSpellConfirm: shop.shouldRestorePackPickOverlayAfterSpellConfirm,
      glyphShopSkipLevelAdvance: run.glyphShopSkipLevelAdvance,
    },
    treasure: {
      ownedTreasures: game.ownedTreasures,
      ownedUpgrades: game.ownedUpgrades,
      ownedVoucherIds: game.ownedVoucherIds,
      ownedSlotTreasureIdList: treasure.ownedSlotTreasureIdList,
      treasureDetail: treasure.treasureDetail,
      treasureRunState: treasure.treasureRunState,
      treasureSession: treasure.treasureSession,
      treasureSlotsLayoutClass: treasure.treasureSlotsLayoutClass,
      treasureGemClass: treasure.treasureGemClass,
      treasureChargeProgressBySlot: treasure.treasureChargeProgressBySlot,
      treasureChargeVisualBySlot: treasure.treasureChargeVisualBySlot,
      treasureEffectDepletedBySlot: treasure.treasureEffectDepletedBySlot,
      displayOwnedTreasures: treasure.displayOwnedTreasures,
      displayOwnedTreasureKeys: treasure.displayOwnedTreasureKeys,
      displayTreasureChargeProgressBySlot: treasure.displayTreasureChargeProgressBySlot,
      displayTreasureChargeVisualBySlot: treasure.displayTreasureChargeVisualBySlot,
      displayTreasureEffectDepletedBySlot: treasure.displayTreasureEffectDepletedBySlot,
      gameOwnedDragActive: treasure.gameOwnedDragActive,
      gameOwnedDragChargeProgress: treasure.gameOwnedDragChargeProgress,
      gameOwnedDragChargeState: treasure.gameOwnedDragChargeState,
      gameOwnedDragEffectDepleted: treasure.gameOwnedDragEffectDepleted,
      gameOwnedDragGhostStyle: treasure.gameOwnedDragGhostStyle,
      gameOwnedDragGhostVisible: treasure.gameOwnedDragGhostVisible,
      gameOwnedDragPlaceholderStyle: treasure.gameOwnedDragPlaceholderStyle,
      gameOwnedDragPlaceholderVisible: treasure.gameOwnedDragPlaceholderVisible,
      gameOwnedDragSourceIndex: treasure.gameOwnedDragSourceIndex,
      gameOwnedKeyOrderBag: treasure.gameOwnedKeyOrderBag,
      findTreasurePlacementIndex: treasure.findTreasurePlacementIndex,
      findOwnedTreasureSlotIndex: treasure.findOwnedTreasureSlotIndex,
      findFirstOwnedTreasureSlotIndex: treasure.findFirstOwnedTreasureSlotIndex,
      grantOwnedTreasureAt: treasure.grantOwnedTreasureAt,
      grantRandomShopTreasure: treasure.grantRandomShopTreasure,
      grantRandomShopTreasureByRarity: treasure.grantRandomShopTreasureByRarity,
      applyTreasureAcquireImmediateEffectsForRun: treasure.applyTreasureAcquireImmediateEffectsForRun,
      runTreasureLevelCompleteHooks: treasure.runTreasureLevelCompleteHooks,
      runTreasurePackOpenPrecursor: treasure.runTreasurePackOpenPrecursor,
      runHourglassStageEndFx: treasure.runHourglassStageEndFx,
      pickCrimsonDisabledTreasureSlotIndex: treasure.pickCrimsonDisabledTreasureSlotIndex,
      crimsonTreasureDisabledSlotIndex: treasure.crimsonTreasureDisabledSlotIndex,
      verdantTreasureSold: run.verdantTreasureSold,
      pillarUsedDeckUids: run.pillarUsedDeckUids,
      presentTreasureDetail: treasure.presentTreasureDetail,
      onGameOwnedSlotPointerDown: treasure.onGameOwnedSlotPointerDown,
      runDetachedTileShrinkReplacePop: treasure.runDetachedTileShrinkReplacePop,
      treasureOriginRectFromEl: treasure.treasureOriginRectFromEl,
    },
    run: {
      runMatchStats: run.runMatchStats,
      runDiscoveryLog: run.runDiscoveryLog,
      runPresetId: run.runPresetId,
      runDifficultyIndex: run.runDifficultyIndex,
      runRandom: run.runRandom,
      runRng: run.runRng,
      runEndCtrlSlot: run.runEndCtrlSlot,
      runEndEnterEndlessImpl: run.runEndEnterEndlessImpl,
      runEndFlowHostRef: run.runEndFlowHostRef,
      runEndOutcome: run.runEndOutcome,
      runEndPortalZ: run.runEndPortalZ,
      runPendingInRunGrantsAfterSubmit: treasure.runPendingInRunGrantsAfterSubmit,
      levelIndex: run.levelIndex,
      currentLevel: run.currentLevel,
      levelTitleBoxRef: run.levelTitleBoxRef,
      levelTitleLabel: run.levelTitleLabel,
      infoModalNextLevelId: run.infoModalNextLevelId,
      money: run.money,
      walletHeaderShown: run.walletHeaderShown,
      targetScore: run.targetScore,
      currentScore: run.currentScore,
      isEndlessRun: run.isEndlessRun,
      activeBossSlug: run.activeBossSlug,
      bossRerollSession: run.bossRerollSession,
      bossSlugForMechanics: run.bossSlugForMechanics,
      mouthLockedLengthBoss: run.mouthLockedLengthBoss,
      clubRequiredKeyBoss: run.clubRequiredKeyBoss,
      usedWordLengthsThisBoss: run.usedWordLengthsThisBoss,
      pendingBossSlugOverride: run.pendingBossSlugOverride,
      pagerQuizSession: run.pagerQuizSession,
      pendingPagerQuizSession: run.pendingPagerQuizSession,
      clearPagerQuizPendingResolve: run.clearPagerQuizPendingResolve,
      achievementRunState: run.achievementRunState,
      mergeCareerOnRunEnd: run.mergeCareerOnRunEnd,
      beginFirstWordTutorialAfterGridSettled: run.beginFirstWordTutorialAfterGridSettled,
      resetLevelAfterTreasurePrep: treasure.resetLevelAfterTreasurePrep,
      lengthLevelsByLength: run.lengthLevelsByLength,
      lengthUpgradeObservatoryExtra: run.lengthUpgradeObservatoryExtra,
      rarityLevelsByRarity: run.rarityLevelsByRarity,
      spellCountsByLength: run.spellCountsByLength,
      recordSpellWordLength: run.recordSpellWordLength,
      lastReplayableSpellId: run.lastReplayableSpellId,
      spellCastHistory: run.spellCastHistory,
      judgedLengthTableLenForRun: run.judgedLengthTableLenForRun,
      runWordLengthJudgmentPenalty: run.runWordLengthJudgmentPenalty,
      setRunWordLengthJudgmentPenalty: run.setRunWordLengthJudgmentPenalty,
      setWordLengthLevel: run.setWordLengthLevel,
      setRarityLevelWithTreasurePairs: run.setRarityLevelWithTreasurePairs,
      bumpWordLengthLevel: run.bumpWordLengthLevel,
      noteCollectionAccessoryAcquired: run.noteCollectionAccessoryAcquired,
      noteCollectionDiscovery: run.noteCollectionDiscovery,
      noteCollectionMaterialAcquired: run.noteCollectionMaterialAcquired,
      noteCollectionUpgradeForWordLen: run.noteCollectionUpgradeForWordLen,
      noteCollectionUpgradeFromRandomPick: run.noteCollectionUpgradeFromRandomPick,
      noteCollectionUpgradeUsed: run.noteCollectionUpgradeUsed,
      noteCollectionWordSubmitted: run.noteCollectionWordSubmitted,
      noteDiscardExhaustedForChapterUnlock: run.noteDiscardExhaustedForChapterUnlock,
      notifyBossRestrictionTreasures: run.notifyBossRestrictionTreasures,
      playBossTapeTriggerCue: run.playBossTapeTriggerCue,
      isAmberBossMaskActive: run.isAmberBossMaskActive,
      isCrimsonBossMechanicsActive: run.isCrimsonBossMechanicsActive,
      evaluateOxBossHit: run.evaluateOxBossHit,
      getBossTileDebuffContext: run.getBossTileDebuffContext,
    },
    overlay: {
      showDeckLayer: overlay.showDeckLayer,
      showInfoLayer: overlay.showInfoLayer,
      showPauseOptions: overlay.showPauseOptions,
      showSettlement: overlay.showSettlement,
      showRunEnd: overlay.showRunEnd,
      showTreasureCollectionLayer: overlay.showTreasureCollectionLayer,
      openInfoModal: overlay.openInfoModal,
      openPauseOptions: overlay.openPauseOptions,
      openPauseOptionsFromShop: overlay.openPauseOptionsFromShop,
      openRunEnd: overlay.openRunEnd,
      openStageSettlementSlot: overlay.openStageSettlementSlot,
      setGameTreasureSlotRef: overlay.setGameTreasureSlotRef,
      runOverlayHostRef: overlay.runOverlayHostRef,
      gamePanelPlayfieldRef: overlay.gamePanelPlayfieldRef,
      firstWordTutorialLayerRef: overlay.firstWordTutorialLayerRef,
      spellTargetSession: overlay.spellTargetSession,
      spellReferencePreview: overlay.spellReferencePreview,
      spellGrantDetailCloseHandler: overlay.spellGrantDetailCloseHandler,
      pendingSpellTileAppearanceAnim: overlay.pendingSpellTileAppearanceAnim,
      wordTranslationInnerRef: overlay.wordTranslationInnerRef,
      wordTranslationWrapRef: overlay.wordTranslationWrapRef,
      transitionBusy: overlay.transitionBusy,
      isRunFlowOverlayOpen: overlay.isRunFlowOverlayOpen,
      isFirstWordTutorialBlockingInput: overlay.isFirstWordTutorialBlockingInput,
      isGamePaused: overlay.isGamePaused,
      showToast: overlay.showToast,
    },
    scoring: {
      canSubmit: scoring.canSubmit,
      resolvedWordForSubmit: scoring.resolvedWordForSubmit,
      effectiveWordForSubmit: scoring.effectiveWordForSubmit,
      effectiveWordPartsForSubmit: scoring.effectiveWordPartsForSubmit,
      buildEffectiveWordPartsForSubmit: scoring.buildEffectiveWordPartsForSubmit,
      resolveWordFromEffectiveParts: scoring.resolveWordFromEffectiveParts,
      listEffectiveTilesForSubmit: scoring.listEffectiveTilesForSubmit,
      buildSubmitAfterLettersContext: scoring.buildSubmitAfterLettersContext,
      applySubmitRefill: scoring.applySubmitRefill,
      applyHookBossAfterSubmit: scoring.applyHookBossAfterSubmit,
      deferredWordSubmitPayload: scoring.deferredWordSubmitPayload,
      submitWordBusy: scoring.submitWordBusy,
      submitDeltaKey: scoring.submitDeltaKey,
      submitTranslationLines: scoring.submitTranslationLines,
      scoringAnimating: scoring.scoringAnimating,
      scoringLetterIndex: scoring.scoringLetterIndex,
      scoringTreasureBarIndex: scoring.scoringTreasureBarIndex,
      rewardDollarMarks: scoring.rewardDollarMarks,
      roundScoreOverride: scoring.roundScoreOverride,
      stageRewardYuan: scoring.stageRewardYuan,
      settlementSnapshot: scoring.settlementSnapshot,
      flashSubmitCountDelta: scoring.flashSubmitCountDelta,
      scheduleStaggeredTileRemoveHaptics: scoring.scheduleStaggeredTileRemoveHaptics,
      getWordDefinition: scoring.getWordDefinition,
      setLastWordFromSubmit: scoring.setLastWordFromSubmit,
      flushDeferredWordSubmitRecord: scoring.flushDeferredWordSubmitRecord,
      flushSubmitAchievements: scoring.flushSubmitAchievements,
      flushAchievementUnlocks: scoring.flushAchievementUnlocks,
      headerRoundScoreValue: scoring.headerRoundScoreValue,
      headerTargetScoreValue: scoring.headerTargetScoreValue,
    },
    fx: {
      pulseFill: fx.pulseFill,
      pulseFormulaPanelNum: fx.pulseFormulaPanelNum,
      pulseFormulaMultMultiplyBurst: fx.pulseFormulaMultMultiplyBurst,
      showScoreBubble: fx.showScoreBubble,
      wobbleScoreSlot: fx.wobbleScoreSlot,
      createWobbleScoreSlotTimeline: fx.createWobbleScoreSlotTimeline,
      awaitWobbleScoreSlotTimeline: fx.awaitWobbleScoreSlotTimeline,
      triggerAccessoryChipRipple: fx.triggerAccessoryChipRipple,
      showMultMultiplyBubble: fx.showMultMultiplyBubble,
      scheduleSmallPlusBubbleOutro: fx.scheduleSmallPlusBubbleOutro,
      scheduleMultMultiplyBubbleOutro: fx.scheduleMultMultiplyBubbleOutro,
      formatMoneyBubbleLabel: fx.formatMoneyBubbleLabel,
      clearAllTreasureSlotWobbleFront: fx.clearAllTreasureSlotWobbleFront,
      wobbleGameTreasureSlot: fx.wobbleGameTreasureSlot,
    },
  };
}

/** early + late controller 接线结果合并为 assembly ctrls 域。 */
export function mergeAssemblyCtrlSection(early, late, overlayStackController) {
  return {
    overlayStackController,
    shopPhase: early.shopPhase,
    treasureInventoryCtrl: early.treasureInventoryCtrl,
    shopTransactionCtrl: early.shopTransactionCtrl,
    runLifecycle: early.runLifecycle,
    tileDetailCtrl: late.tileDetailCtrl,
    runResultPresentationCtrl: late.runResultPresentationCtrl,
    bossMechanicsCtrl: late.bossMechanicsCtrl,
    wordDefinitionCtrl: late.wordDefinitionCtrl,
    gpWordSlotPresentation: late.gpWordSlotPresentation,
  };
}

/** wireGamePanelControllers early 返回值 → assembly treasure 域字段。 */
export function buildAssemblyTreasureSection(early, gpExtras) {
  return {
    ownedSlotTreasureIdList: early.ownedSlotTreasureIdListFromController ?? gpExtras.ownedSlotTreasureIdList,
    treasureDetail: gpExtras.treasureDetail,
    treasureRunState: gpExtras.treasureRunState,
    treasureSession: early.treasureSession,
    treasureSlotsLayoutClass: gpExtras.treasureSlotsLayoutClass,
    treasureGemClass: gpExtras.treasureGemClass,
    treasureChargeProgressBySlot: early.treasureChargeProgressBySlot,
    treasureChargeVisualBySlot: early.treasureChargeVisualBySlot,
    treasureEffectDepletedBySlot: early.treasureEffectDepletedBySlot,
    displayOwnedTreasures: early.displayOwnedTreasures,
    displayOwnedTreasureKeys: early.displayOwnedTreasureKeys,
    displayTreasureChargeProgressBySlot: early.displayTreasureChargeProgressBySlot,
    displayTreasureChargeVisualBySlot: early.displayTreasureChargeVisualBySlot,
    displayTreasureEffectDepletedBySlot: early.displayTreasureEffectDepletedBySlot,
    gameOwnedDragActive: early.gameOwnedDragActive,
    gameOwnedDragChargeProgress: early.gameOwnedDragChargeProgress,
    gameOwnedDragChargeState: early.gameOwnedDragChargeState,
    gameOwnedDragEffectDepleted: early.gameOwnedDragEffectDepleted,
    gameOwnedDragGhostStyle: early.gameOwnedDragGhostStyle,
    gameOwnedDragGhostVisible: early.gameOwnedDragGhostVisible,
    gameOwnedDragPlaceholderStyle: early.gameOwnedDragPlaceholderStyle,
    gameOwnedDragPlaceholderVisible: early.gameOwnedDragPlaceholderVisible,
    gameOwnedDragSourceIndex: early.gameOwnedDragSourceIndex,
    gameOwnedKeyOrderBag: early.gameOwnedKeyOrderBag,
    findTreasurePlacementIndex: early.findTreasurePlacementIndex,
    findOwnedTreasureSlotIndex: early.findOwnedTreasureSlotIndex,
    findFirstOwnedTreasureSlotIndex: gpExtras.findFirstOwnedTreasureSlotIndex,
    grantOwnedTreasureAt: early.grantOwnedTreasureAt,
    grantRandomShopTreasure: gpExtras.grantRandomShopTreasure,
    grantRandomShopTreasureByRarity: gpExtras.grantRandomShopTreasureByRarity,
    applyTreasureAcquireImmediateEffectsForRun: early.applyTreasureAcquireImmediateEffectsForRun,
    runTreasureLevelCompleteHooks: early.runTreasureLevelCompleteHooks,
    runTreasurePackOpenPrecursor: gpExtras.runTreasurePackOpenPrecursor,
    runHourglassStageEndFx: gpExtras.runHourglassStageEndFx,
    pickCrimsonDisabledTreasureSlotIndex: gpExtras.pickCrimsonDisabledTreasureSlotIndex,
    crimsonTreasureDisabledSlotIndex: gpExtras.crimsonTreasureDisabledSlotIndex,
    presentTreasureDetail: early.presentTreasureDetail,
    onGameOwnedSlotPointerDown: early.onGameOwnedSlotPointerDown,
    runDetachedTileShrinkReplacePop: gpExtras.runDetachedTileShrinkReplacePop,
    treasureOriginRectFromEl: gpExtras.treasureOriginRectFromEl,
    appendShopDeckEntriesAndNotify: early.appendShopDeckEntriesAndNotify,
    buildShopOwnedPreviewNavItems: early.buildShopOwnedPreviewNavItems,
    canPlaceTreasureOffer: early.canPlaceTreasureOffer,
    notifyShopLeave: early.notifyShopLeave,
    runPendingInRunGrantsAfterSubmit: early.runPendingInRunGrantsAfterSubmit,
    resetLevelAfterTreasurePrep: early.resetLevelAfterTreasurePrep,
  };
}

/** @param {Record<string, unknown>} early @param {Record<string, unknown>} gpExtras */
export function buildAssemblyRunSection(early, gpExtras) {
  return {
    runMatchStats: gpExtras.runMatchStats,
    runDiscoveryLog: gpExtras.runDiscoveryLog,
    runPresetId: gpExtras.runPresetId,
    runDifficultyIndex: gpExtras.runDifficultyIndex,
    runRandom: gpExtras.runRandom,
    runRng: gpExtras.runRng,
    runEndCtrlSlot: gpExtras.runEndCtrlSlot,
    runEndEnterEndlessImpl: gpExtras.runEndEnterEndlessImpl,
    runEndFlowHostRef: gpExtras.runEndFlowHostRef,
    runEndOutcome: early.runEndOutcome,
    runEndPortalZ: early.runEndPortalZ,
    levelIndex: gpExtras.levelIndex,
    currentLevel: early.currentLevel,
    levelTitleBoxRef: early.levelTitleBoxRef,
    levelTitleLabel: early.levelTitleLabel,
    infoModalNextLevelId: early.infoModalNextLevelId,
    money: gpExtras.money,
    walletHeaderShown: early.walletHeaderShown,
    targetScore: gpExtras.targetScore,
    currentScore: gpExtras.currentScore,
    isEndlessRun: gpExtras.isEndlessRun,
    activeBossSlug: gpExtras.activeBossSlug,
    bossRerollSession: early.bossRerollSession,
    bossSlugForMechanics: gpExtras.bossSlugForMechanics,
    mouthLockedLengthBoss: early.mouthLockedLengthBoss,
    clubRequiredKeyBoss: early.clubRequiredKeyBoss,
    usedWordLengthsThisBoss: early.usedWordLengthsThisBoss,
    pendingBossSlugOverride: early.pendingBossSlugOverride,
    pagerQuizSession: early.pagerQuizSession,
    pendingPagerQuizSession: early.pendingPagerQuizSession,
    clearPagerQuizPendingResolve: early.clearPagerQuizPendingResolve,
    achievementRunState: gpExtras.achievementRunState,
    mergeCareerOnRunEnd: gpExtras.mergeCareerOnRunEnd,
    beginFirstWordTutorialAfterGridSettled: gpExtras.beginFirstWordTutorialAfterGridSettled,
    lengthLevelsByLength: gpExtras.lengthLevelsByLength,
    lengthUpgradeObservatoryExtra: gpExtras.lengthUpgradeObservatoryExtra,
    rarityLevelsByRarity: gpExtras.rarityLevelsByRarity,
    spellCountsByLength: gpExtras.spellCountsByLength,
    recordSpellWordLength: gpExtras.recordSpellWordLength,
    lastReplayableSpellId: gpExtras.lastReplayableSpellId,
    spellCastHistory: gpExtras.spellCastHistory,
    judgedLengthTableLenForRun: gpExtras.judgedLengthTableLenForRun,
    runWordLengthJudgmentPenalty: gpExtras.runWordLengthJudgmentPenalty,
    setRunWordLengthJudgmentPenalty: gpExtras.setRunWordLengthJudgmentPenalty,
    setWordLengthLevel: gpExtras.setWordLengthLevel,
    setRarityLevelWithTreasurePairs: gpExtras.setRarityLevelWithTreasurePairs,
    bumpWordLengthLevel: gpExtras.bumpWordLengthLevel,
    noteCollectionAccessoryAcquired: gpExtras.noteCollectionAccessoryAcquired,
    noteCollectionDiscovery: gpExtras.noteCollectionDiscovery,
    noteCollectionMaterialAcquired: gpExtras.noteCollectionMaterialAcquired,
    noteCollectionUpgradeForWordLen: gpExtras.noteCollectionUpgradeForWordLen,
    noteCollectionUpgradeFromRandomPick: gpExtras.noteCollectionUpgradeFromRandomPick,
    noteCollectionUpgradeUsed: gpExtras.noteCollectionUpgradeUsed,
    noteCollectionWordSubmitted: gpExtras.noteCollectionWordSubmitted,
    noteDiscardExhaustedForChapterUnlock: gpExtras.noteDiscardExhaustedForChapterUnlock,
    notifyBossRestrictionTreasures: early.notifyBossRestrictionTreasures,
    playBossTapeTriggerCue: gpExtras.playBossTapeTriggerCue,
    isAmberBossMaskActive: gpExtras.isAmberBossMaskActive,
    isCrimsonBossMechanicsActive: gpExtras.isCrimsonBossMechanicsActive,
    evaluateOxBossHit: gpExtras.evaluateOxBossHit,
    getBossTileDebuffContext: gpExtras.getBossTileDebuffContext,
    onShopNextLevel: early.onShopNextLevel,
    glyphShopSkipLevelAdvance: early.glyphShopSkipLevelAdvance,
    pillarUsedDeckUids: gpExtras.pillarUsedDeckUids,
    verdantTreasureSold: gpExtras.verdantTreasureSold,
  };
}

/** @param {Record<string, unknown>} early @param {Record<string, unknown>} gpExtras @param {Record<string, unknown>} playfieldSubmit */
export function buildAssemblyScoringSection(early, gpExtras, playfieldSubmit) {
  return {
    canSubmit: gpExtras.canSubmit,
    resolvedWordForSubmit: playfieldSubmit.resolvedWordForSubmit,
    effectiveWordForSubmit: playfieldSubmit.effectiveWordForSubmit,
    effectiveWordPartsForSubmit: playfieldSubmit.effectiveWordPartsForSubmit,
    buildEffectiveWordPartsForSubmit: playfieldSubmit.buildEffectiveWordPartsForSubmit,
    resolveWordFromEffectiveParts: playfieldSubmit.resolveWordFromEffectiveParts,
    listEffectiveTilesForSubmit: playfieldSubmit.listEffectiveTilesForSubmit,
    resolveRealSubmitTileForWordSlot: playfieldSubmit.resolveRealSubmitTileForWordSlot,
    buildSubmitAfterLettersContext: gpExtras.buildSubmitAfterLettersContext,
    applySubmitRefill: gpExtras.applySubmitRefill,
    applyHookBossAfterSubmit: gpExtras.applyHookBossAfterSubmit,
    deferredWordSubmitPayload: gpExtras.deferredWordSubmitPayload,
    submitWordBusy: gpExtras.submitWordBusy,
    submitDeltaKey: gpExtras.submitDeltaKey,
    submitTranslationLines: gpExtras.submitTranslationLines,
    scoringAnimating: gpExtras.scoringAnimating,
    scoringLetterIndex: gpExtras.scoringLetterIndex,
    scoringTreasureBarIndex: gpExtras.scoringTreasureBarIndex,
    rewardDollarMarks: early.rewardDollarMarks,
    roundScoreOverride: early.roundScoreOverride,
    stageRewardYuan: early.stageRewardYuan,
    settlementSnapshot: early.settlementSnapshot,
    flashSubmitCountDelta: gpExtras.flashSubmitCountDelta,
    scheduleStaggeredTileRemoveHaptics: gpExtras.scheduleStaggeredTileRemoveHaptics,
    getWordDefinition: gpExtras.getWordDefinition,
    setLastWordFromSubmit: gpExtras.setLastWordFromSubmit,
    flushDeferredWordSubmitRecord: gpExtras.flushDeferredWordSubmitRecord,
    flushSubmitAchievements: gpExtras.flushSubmitAchievements,
    flushAchievementUnlocks: gpExtras.flushAchievementUnlocks,
    headerRoundScoreValue: early.headerRoundScoreValue,
    headerTargetScoreValue: early.headerTargetScoreValue,
  };
}

/**
 * GamePanel 装配 wiring → 8 域 sections（GP 只传分组 ctx，映射在此完成）。
 * @param {{
 *   gp: Record<string, unknown>,
 *   ctrlEarly: Record<string, unknown>,
 *   ctrlLate: Record<string, unknown>,
 *   overlayStackController: unknown,
 *   playfieldSubmit: Record<string, unknown>,
 *   game: Record<string, unknown>,
 *   playfield: Record<string, unknown>,
 *   shop: Record<string, unknown>,
 *   treasureExtras: Record<string, unknown>,
 *   runExtras: Record<string, unknown>,
 *   overlay: Record<string, unknown>,
 *   scoringExtras: Record<string, unknown>,
 *   fx: Record<string, unknown>,
 * }} w
 */
export function buildGamePanelAssemblyFromWiring(w) {
  return collectGamePanelAssemblySections({
    gp: w.gp,
    ctrls: mergeAssemblyCtrlSection(w.ctrlEarly, w.ctrlLate, w.overlayStackController),
    game: w.game,
    playfield: w.playfield,
    shop: w.shop,
    treasure: buildAssemblyTreasureSection(w.ctrlEarly, w.treasureExtras),
    run: buildAssemblyRunSection(w.ctrlEarly, w.runExtras),
    overlay: w.overlay,
    scoring: buildAssemblyScoringSection(w.ctrlEarly, w.scoringExtras, w.playfieldSubmit),
    fx: w.fx,
  });
}
