import { wireAllGamePanelFx } from "./wireGamePanelFx.js";

/**
 * GamePanel FX 工厂 deps 构建并接线。
 * @param {object} d
 */
export function wireGamePanelFxFromDeps(d) {
  wireAllGamePanelFx({
    ownedBar: {
      ownedBarFxRef: d.ownedBarFxRef,
      nextTick: d.nextTick,
      findOwnedTreasureSlotIndex: d.findOwnedTreasureSlotIndex,
      findAllOwnedTreasureSlotIndices: d.findAllOwnedTreasureSlotIndices,
      treasureInventoryCtrl: d.treasureInventoryCtrl,
      shopOverlayLayersSuppressed: d.shopOverlayLayersSuppressed,
      scoringTreasureBarIndex: d.scoringTreasureBarIndex,
      money: d.money,
      wobbleGameTreasureSlot: d.wobbleGameTreasureSlot,
      wobbleScoreSlot: d.wobbleScoreSlot,
      showScoreBubble: d.showScoreBubble,
      scheduleSmallPlusBubbleOutro: d.scheduleSmallPlusBubbleOutro,
      formatMoneyBubbleLabel: d.formatMoneyBubbleLabel,
      bumpOverlayZ: d.bumpOverlayZ,
      scoringLetterGapMs: d.scoringLetterGapMs,
    },
    destroy: {
      treasureDestroyFxRef: d.treasureDestroyFxRef,
      findOwnedTreasureSlotIndex: d.findOwnedTreasureSlotIndex,
      ownedTreasureHasNoSellAccessory: d.ownedTreasureHasNoSellAccessory,
      isTreasureBarSlotVisible: d.isTreasureBarSlotVisible,
      treasureInventoryCtrl: d.treasureInventoryCtrl,
      ownedTreasures: d.ownedTreasures,
      removeOwnedTreasureSlotsLeaveGapAtIndices: d.removeOwnedTreasureSlotsLeaveGapAtIndices,
      scheduleRunAutoSave: d.scheduleRunAutoSave,
      wobbleGameTreasureSlot: d.wobbleGameTreasureSlot,
      showScoreBubble: d.showScoreBubble,
      scheduleSmallPlusBubbleOutro: d.scheduleSmallPlusBubbleOutro,
      createWobbleScoreSlotTimeline: d.createWobbleScoreSlotTimeline,
      awaitWobbleScoreSlotTimeline: d.awaitWobbleScoreSlotTimeline,
      playOwnedTreasureWobbleOnlyFx: d.playOwnedTreasureWobbleOnlyFx,
      shopOverlayLayersSuppressed: d.shopOverlayLayersSuppressed,
      nextTick: d.nextTick,
      onBombBlastResolved: d.onBombBlastResolved,
    },
    volcano: {
      treasureLevelCompleteFxRef: d.treasureLevelCompleteFxRef,
      treasureDestroyFxRef: d.treasureDestroyFxRef,
      ownedTreasures: d.ownedTreasures,
      grid: d.grid,
      ROWS: d.ROWS,
      COLS: d.COLS,
      treasureInventoryCtrl: d.treasureInventoryCtrl,
      ownedTreasureHasNoSellAccessory: d.ownedTreasureHasNoSellAccessory,
      isTreasureBarSlotVisible: d.isTreasureBarSlotVisible,
      showScoreBubble: d.showScoreBubble,
      scheduleSmallPlusBubbleOutro: d.scheduleSmallPlusBubbleOutro,
      clearOwnedTreasureSlotLeaveGapAtIndex: d.clearOwnedTreasureSlotLeaveGapAtIndex,
      scheduleRunAutoSave: d.scheduleRunAutoSave,
      touchGrid: d.touchGrid,
      nextTick: d.nextTick,
      shopOverlayLayersSuppressed: d.shopOverlayLayersSuppressed,
      scoreBubbleAnchorRect: d.scoreBubbleAnchorRect,
      getGridTileElByIndex: d.getGridTileElByIndex,
      onVolcanoEruptionPlayed: d.onVolcanoEruptionPlayed,
    },
    hourglass: {
      hourglassStageFxRef: d.hourglassStageFxRef,
      ownedTreasures: d.ownedTreasures,
      wobbleScoreSlot: d.wobbleScoreSlot,
      treasureInventoryCtrl: d.treasureInventoryCtrl,
      showScoreBubble: d.showScoreBubble,
      scheduleSmallPlusBubbleOutro: d.scheduleSmallPlusBubbleOutro,
      scheduleRunAutoSave: d.scheduleRunAutoSave,
    },
    inRunUpgrade: {
      inRunUpgradePlaybackRef: d.inRunUpgradePlaybackRef,
      runResultPresentationCtrl: d.runResultPresentationCtrl,
      shopOverlayLayersSuppressed: d.shopOverlayLayersSuppressed,
      nextTick: d.nextTick,
      sleep: d.sleep,
      submitAccessoryUpgradeBatchState: d.submitAccessoryUpgradeBatchState,
    },
    submitLeave: {
      submitTileLeaveFxRef: d.submitTileLeaveFxRef,
      treasureRunState: d.treasureRunState,
      getSelectedGridTileElsInOrder: d.getSelectedGridTileElsInOrder,
      getWordSlotRefs: d.getWordSlotRefs,
      findOwnedTreasureSlotIndex: d.findOwnedTreasureSlotIndex,
      runRandom: d.runRandom,
      isBossTileDebuffed: d.isBossTileDebuffed,
      removeDeckCardByUidAndNotify: d.removeDeckCardByUidAndNotify,
      ownedSlotTreasureIdList: d.ownedSlotTreasureIdList,
      ownedTreasureHookFxBridge: d.ownedTreasureHookFxBridge,
      playTreasureSlotBubbleBurstAtPeak: d.playTreasureSlotBubbleBurstAtPeak,
      ownedBarFxRef: d.ownedBarFxRef,
      playOwnedTreasureMoneyFx: d.playOwnedTreasureMoneyFx,
      wobbleGameTreasureSlot: d.wobbleGameTreasureSlot,
      triggerHaptic: d.triggerHaptic,
      touchGrid: d.touchGrid,
      showScoreBubble: d.showScoreBubble,
      createWobbleScoreSlotTimeline: d.createWobbleScoreSlotTimeline,
      awaitTreasureSlotWobbleElForSubmit: d.awaitTreasureSlotWobbleElForSubmit,
      runDetachedTileShrinkReplacePop: d.runDetachedTileShrinkReplacePop,
      scheduleSmallPlusBubbleOutro: d.scheduleSmallPlusBubbleOutro,
      sleep: d.sleep,
      nextTick: d.nextTick,
    },
  });
}
