/**
 * Playfield ViewContext 字段组装（S.7 / 任务 8.5）。
 * @param {Record<string, unknown>} extras GamePanel / 跨域 refs、handlers
 * @param {Record<string, unknown>} pf `usePlayfieldController` 导出
 */
export function assemblePlayfieldViewContext(extras, pf) {
  return {
    ...extras,
    ROWS: pf.ROWS,
    COLS: pf.COLS,
    displayWordSlotPresentations: pf.displayWordSlotPresentations,
    tileDragActive: pf.tileDragActive,
    wordSlotPlaceholderKey: pf.wordSlotPlaceholderKey,
    setWordSlotRef: pf.setWordSlotRef,
    isSlotOutOfFlow: pf.isSlotOutOfFlow,
    onSlotClick: pf.onSlotClick,
    onWordSlotContextMenu: pf.onWordSlotContextMenu,
    onWordSlotCombinedPointerDown: pf.onWordSlotCombinedPointerDown,
    onWordSlotPointerUp: pf.onWordSlotPointerUp,
    onTilePointerCancel: pf.onTilePointerCancel,
    tileDragGhostPresentation: pf.tileDragGhostPresentation,
    tileDragGhostVisible: pf.tileDragGhostVisible,
    tileDragGhostStyle: pf.tileDragGhostStyle,
    flyingLettersForRender: pf.flyingLettersForRender,
    setFlyingInRef: pf.setFlyingInRef,
    isSlotContentHidden: pf.isSlotContentHidden,
    flatGrid: pf.flatGrid,
    isGridTilePlaceholder: pf.isGridTilePlaceholder,
    gridTileRenderMemoDeps: pf.gridTileRenderMemoDeps,
    gridTileRenderLetter: pf.gridTileRenderLetter,
    gridTileRenderRarity: pf.gridTileRenderRarity,
    gridPlaceholderFrozenPresentation: pf.gridPlaceholderFrozenPresentation,
    gridTileRenderVowelGhostPrev: pf.gridTileRenderVowelGhostPrev,
    gridTileRenderVowelGhostNext: pf.gridTileRenderVowelGhostNext,
    setGridTileRef: pf.setGridTileRef,
    isTileFlying: pf.isTileFlying,
    onTileClick: pf.onTileClick,
    onGridTileContextMenu: pf.onGridTileContextMenu,
    onGridTileCombinedPointerDown: pf.onGridTileCombinedPointerDown,
    onGridTilePointerUp: pf.onGridTilePointerUp,
    tileDragGridPlaceholderVisible: pf.tileDragGridPlaceholderVisible,
    tileDragGridPlaceholderStyle: pf.tileDragGridPlaceholderStyle,
    showMarkButtonInRun: pf.showMarkButtonInRun,
    showSwapWordButtonInRun: pf.showSwapWordButtonInRun,
    canUseMarkButton: pf.canUseMarkButton,
    markButtonTitle: pf.markButtonTitle,
    onMarkButtonClick: pf.onMarkButtonClick,
    showMarkSendArrow: pf.showMarkSendArrow,
    canSwapWordSelection: pf.canSwapWordSelection,
    swapWordButtonTitle: pf.swapWordButtonTitle,
    onSwapWordSelectionClick: pf.onSwapWordSelectionClick,
    flyingLetters: pf.flyingLetters,
    flyingBackBatches: pf.flyingBackBatches,
  };
}
