/** @typedef {ReturnType<typeof createPlayfieldPorts>} PlayfieldPort */

/** @typedef {import('./playfieldPortTypes.js').PlayfieldPortBinding} PlayfieldPortBinding */

/**
 * 棋盘/字母库域 assembly 端口（R4.2）。
 * @param {PlayfieldPortBinding} binding
 */
export function createPlayfieldPorts(binding) {
  return Object.freeze({
    grid: binding.grid,
    gridIntroDone: binding.gridIntroDone,
    gridRefillAnimating: binding.gridRefillAnimating,
    gridTileRefs: binding.gridTileRefs,
    selectedOrder: binding.selectedOrder,
    selectedTiles: binding.selectedTiles,
    selectTile: binding.selectTile,
    removeFromSlot: binding.removeFromSlot,
    removeSingleTileFromWord: binding.removeSingleTileFromWord,
    insertSelectedTileAt: binding.insertSelectedTileAt,
    reorderSelectedOrder: binding.reorderSelectedOrder,
    removeSelectedLetters: binding.removeSelectedLetters,
    touchGrid: binding.touchGrid,
    flatGrid: binding.flatGrid,
    snapshotGridCellsByTileId: binding.snapshotGridCellsByTileId,
    syncPlayerMarkBatchCounterFromGrid: binding.syncPlayerMarkBatchCounterFromGrid,
    ensureSlotRafRunning: binding.ensureSlotRafRunning,
    updateSlotPositions: binding.updateSlotPositions,
    letterGridRef: binding.letterGridRef,
    letterGridWrapRef: binding.letterGridWrapRef,
    wordSlotRefs: binding.wordSlotRefs,
    wordSlotsWrapRef: binding.wordSlotsWrapRef,
    wordSlotsScaleRootRef: binding.wordSlotsScaleRootRef,
    submitBtnRef: binding.submitBtnRef,
    submitBookmarkRef: binding.submitBookmarkRef,
    hintBtnRef: binding.hintBtnRef,
    getGridTileElByIndex: binding.getGridTileElByIndex,
    getSelectedGridCellElsInOrder: binding.getSelectedGridCellElsInOrder,
    ceruleanBellSlotIndex: binding.ceruleanBellSlotIndex,
    finalizeCeruleanBellSlotIndex: binding.finalizeCeruleanBellSlotIndex,
    ensureCeruleanBellMarkedOnGrid: binding.ensureCeruleanBellMarkedOnGrid,
    findCeruleanBellLockedTileOnGrid: binding.findCeruleanBellLockedTileOnGrid,
    markTileAsWildcard: binding.markTileAsWildcard,
    remapTileFromRawLetter: binding.remapTileFromRawLetter,
    refreshGridTileBaseScoresFromLevels: binding.refreshGridTileBaseScoresFromLevels,
    refreshBossTileDebuffOnTile: binding.refreshBossTileDebuffOnTile,
    isManacleBossGrid: binding.isManacleBossGrid,
    suppressTilePrimaryClick: binding.suppressTilePrimaryClick,
    wordSelectionSwapBusy: binding.wordSelectionSwapBusy,
    flyingLetters: binding.flyingLetters,
    flyingBackBatches: binding.flyingBackBatches,
    deck: binding.deck,
    deckBtnRef: binding.deckBtnRef,
    deckCount: binding.deckCount,
    deckPreview: binding.deckPreview,
    exportDeckState: binding.exportDeckState,
    hydrateDeckState: binding.hydrateDeckState,
    initialDeckSnapshot: binding.initialDeckSnapshot,
    removeDeckCardByUid: binding.removeDeckCardByUid,
    removeDeckCardByUidAndNotify: binding.removeDeckCardByUidAndNotify,
    removeDeckCardsForSubmittedWord: binding.removeDeckCardsForSubmittedWord,
    removeDeckCardsForSubmittedWordAndNotify: binding.removeDeckCardsForSubmittedWordAndNotify,
    removeDeckLetterInstancesByRaws: binding.removeDeckLetterInstancesByRaws,
    removeDeckLettersByRawsWithTreasureNotify: binding.removeDeckLettersByRawsWithTreasureNotify,
    appendShopDeckEntries: binding.appendShopDeckEntries,
    appendShopDeckEntriesAndNotify: binding.appendShopDeckEntriesAndNotify,
    getInRunDeckFlyTargetEl: binding.getInRunDeckFlyTargetEl,
    remainingRemovals: binding.remainingRemovals,
    remainingWords: binding.remainingWords,
    hintRemaining: binding.hintRemaining,
    pendingHintChargeWord: binding.pendingHintChargeWord,
    basketballWordsSubmitted: binding.basketballWordsSubmitted,
    dictFatalError: binding.dictFatalError,
    dictionaryReady: binding.dictionaryReady,
  });
}
