/** @typedef {ReturnType<typeof createRunPorts>} RunPort */

/** @typedef {import('./runPortTypes.js').RunPortBinding} RunPortBinding */

/**
 * 局内 run / Boss / 关卡 progression 域 assembly 端口（R4.4）。
 * @param {RunPortBinding} binding
 */
export function createRunPorts(binding) {
  return Object.freeze({
    runLifecycle: binding.runLifecycle,
    runMatchStats: binding.runMatchStats,
    runDiscoveryLog: binding.runDiscoveryLog,
    runPresetId: binding.runPresetId,
    runDifficultyIndex: binding.runDifficultyIndex,
    runRandom: binding.runRandom,
    runRng: binding.runRng,
    runWalletFloor: binding.runWalletFloor,
    runEndCtrlSlot: binding.runEndCtrlSlot,
    runEndEnterEndlessImpl: binding.runEndEnterEndlessImpl,
    runEndFlowHostRef: binding.runEndFlowHostRef,
    runEndOutcome: binding.runEndOutcome,
    runEndPortalZ: binding.runEndPortalZ,
    runPendingInRunGrantsAfterSubmit: binding.runPendingInRunGrantsAfterSubmit,
    levelIndex: binding.levelIndex,
    currentLevel: binding.currentLevel,
    levelTitleBoxRef: binding.levelTitleBoxRef,
    levelTitleLabel: binding.levelTitleLabel,
    infoModalNextLevelId: binding.infoModalNextLevelId,
    money: binding.money,
    walletHeaderShown: binding.walletHeaderShown,
    targetScore: binding.targetScore,
    currentScore: binding.currentScore,
    isEndlessRun: binding.isEndlessRun,
    activeBossSlug: binding.activeBossSlug,
    bossRerollSession: binding.bossRerollSession,
    bossSlugForMechanics: binding.bossSlugForMechanics,
    bossTapeSoftPreview: binding.bossTapeSoftPreview,
    bossMechanicsSuppressed: binding.bossMechanicsSuppressed,
    mouthLockedLengthBoss: binding.mouthLockedLengthBoss,
    clubRequiredKeyBoss: binding.clubRequiredKeyBoss,
    usedWordLengthsThisBoss: binding.usedWordLengthsThisBoss,
    pendingBossSlugOverride: binding.pendingBossSlugOverride,
    pagerQuizSession: binding.pagerQuizSession,
    pendingPagerQuizSession: binding.pendingPagerQuizSession,
    clearPagerQuizPendingResolve: binding.clearPagerQuizPendingResolve,
    achievementRunState: binding.achievementRunState,
    mergeCareerOnRunEnd: binding.mergeCareerOnRunEnd,
    beginFirstWordTutorialAfterGridSettled: binding.beginFirstWordTutorialAfterGridSettled,
    resetLevelAfterTreasurePrep: binding.resetLevelAfterTreasurePrep,
    lengthLevelsByLength: binding.lengthLevelsByLength,
    lengthUpgradeObservatoryExtra: binding.lengthUpgradeObservatoryExtra,
    rarityLevelsByRarity: binding.rarityLevelsByRarity,
    spellCountsByLength: binding.spellCountsByLength,
    recordSpellWordLength: binding.recordSpellWordLength,
    lastReplayableSpellId: binding.lastReplayableSpellId,
    spellCastHistory: binding.spellCastHistory,
    judgedLengthTableLenForRun: binding.judgedLengthTableLenForRun,
    runWordLengthJudgmentPenalty: binding.runWordLengthJudgmentPenalty,
    setRunWordLengthJudgmentPenalty: binding.setRunWordLengthJudgmentPenalty,
    setWordLengthLevel: binding.setWordLengthLevel,
    setRarityLevelWithTreasurePairs: binding.setRarityLevelWithTreasurePairs,
    bumpWordLengthLevel: binding.bumpWordLengthLevel,
    noteCollectionAccessoryAcquired: binding.noteCollectionAccessoryAcquired,
    noteCollectionDiscovery: binding.noteCollectionDiscovery,
    noteCollectionMaterialAcquired: binding.noteCollectionMaterialAcquired,
    noteCollectionUpgradeForWordLen: binding.noteCollectionUpgradeForWordLen,
    noteCollectionUpgradeFromRandomPick: binding.noteCollectionUpgradeFromRandomPick,
    noteCollectionUpgradeUsed: binding.noteCollectionUpgradeUsed,
    noteCollectionWordSubmitted: binding.noteCollectionWordSubmitted,
    noteDiscardExhaustedForChapterUnlock: binding.noteDiscardExhaustedForChapterUnlock,
    notifyBossRestrictionTreasures: binding.notifyBossRestrictionTreasures,
    playBossTapeTriggerCue: binding.playBossTapeTriggerCue,
    isAmberBossMaskActive: binding.isAmberBossMaskActive,
    isCrimsonBossMechanicsActive: binding.isCrimsonBossMechanicsActive,
    isFlintBossActive: binding.isFlintBossActive,
    evaluateOxBossHit: binding.evaluateOxBossHit,
    getBossTileDebuffContext: binding.getBossTileDebuffContext,
    armBossDowngradeFxModel: binding.armBossDowngradeFxModel,
    armBossLengthDowngradeFxActive: binding.armBossLengthDowngradeFxActive,
    clearWinFxModel: binding.clearWinFxModel,
    clearWinLengthUpgradeFxActive: binding.clearWinLengthUpgradeFxActive,
    lastSubmitRarityFxActive: binding.lastSubmitRarityFxActive,
    lastSubmitRarityFxModel: binding.lastSubmitRarityFxModel,
  });
}
