/**
 * 宝藏展示、脚本路径与实现状态目录（集中维护）。
 *
 * `collectionOrder`（可选）：收藏页同稀有度、同解锁条件组内的排序；数值越小越靠前。
 * 未指定时按 `treasureId` 排在所有已指定项之后。建议用 0、10、20… 留空隙便于日后插入。
 *
 * `introducedVersion`（可选）：宝藏首次加入游戏的版本；未指定时视为 {@link DEFAULT_TREASURE_INTRODUCED_VERSION}。
 */
export const DEFAULT_TREASURE_INTRODUCED_VERSION = "1.0.0";

export const TREASURE_CATALOG = [
  { treasureId: "1", name: "火花", emoji: "✨", scriptPath: "./items/treasure_1.js", implemented: true },
  { treasureId: "2", name: "铅笔", emoji: "✏️", scriptPath: "./items/treasure_2.js", implemented: true },
  { treasureId: "3", name: "宝石", emoji: "💎", scriptPath: "./items/treasure_3.js", implemented: true },
  { treasureId: "4", name: "水晶球", emoji: "🔮", scriptPath: "./items/treasure_4.js", implemented: true },
  { treasureId: "5", name: "王冠", emoji: "👑", scriptPath: "./items/treasure_5.js", implemented: true },
  { treasureId: "6", name: "链条", emoji: "⛓️", scriptPath: "./items/treasure_6.js", implemented: true },
  { treasureId: "7", name: "扩音器", emoji: "📢", scriptPath: "./items/treasure_7.js", implemented: true },
  { treasureId: "8", name: "放大镜", emoji: "🔍", scriptPath: "./items/treasure_8.js", implemented: true },
  { treasureId: "9", name: "拼图", emoji: "🧩", scriptPath: "./items/treasure_9.js", implemented: true },
  { treasureId: "10", name: "公文包", emoji: "💼", scriptPath: "./items/treasure_10.js", implemented: true },
  { treasureId: "11", name: "键盘", emoji: "⌨️", scriptPath: "./items/treasure_11.js", implemented: true },
  { treasureId: "12", name: "碗", emoji: "🥣", scriptPath: "./items/treasure_12.js", implemented: true },
  { treasureId: "13", name: "雪花", emoji: "❄️", scriptPath: "./items/treasure_13.js", implemented: true },
  { treasureId: "14", name: "调色盘", emoji: "🎨", scriptPath: "./items/treasure_14.js", implemented: true },
  { treasureId: "15", name: "丝带", emoji: "🎗️", scriptPath: "./items/treasure_15.js", implemented: true },
  { treasureId: "16", name: "沙漏", emoji: "⌛", scriptPath: "./items/treasure_16.js", implemented: true },
  { treasureId: "17", name: "椅子", emoji: "🪑", scriptPath: "./items/treasure_17.js", implemented: true },
  { treasureId: "18", name: "手包", emoji: "👝", scriptPath: "./items/treasure_18.js", implemented: true },
  { treasureId: "19", name: "火", emoji: "🔥", scriptPath: "./items/treasure_19.js", implemented: true },
  { treasureId: "20", name: "篮球", emoji: "🏀", scriptPath: "./items/treasure_20.js", implemented: true },
  { treasureId: "21", name: "靶心", emoji: "🎯", scriptPath: "./items/treasure_21.js", implemented: true },
  { treasureId: "22", name: "号角", emoji: "📯", scriptPath: "./items/treasure_22.js", implemented: true },
  { treasureId: "23", name: "算盘", emoji: "🧮", scriptPath: "./items/treasure_23.js", implemented: true },
  { treasureId: "24", name: "小票", emoji: "🧾", scriptPath: "./items/treasure_24.js", implemented: true },
  { treasureId: "25", name: "海螺", emoji: "🐚", scriptPath: "./items/treasure_25.js", implemented: true },
  { treasureId: "26", name: "书本", emoji: "📚", scriptPath: "./items/treasure_26.js", implemented: true },
  { treasureId: "27", name: "硬币", emoji: "🪙", scriptPath: "./items/treasure_27.js", implemented: true },
  { treasureId: "28", name: "乐谱", emoji: "🎼", scriptPath: "./items/treasure_28.js", implemented: true },
  { treasureId: "29", name: "炸弹", emoji: "💣", scriptPath: "./items/treasure_29.js", implemented: true },
  { treasureId: "30", name: "试管", emoji: "🧪", scriptPath: "./items/treasure_30.js", implemented: true },
  { treasureId: "31", name: "锤子", emoji: "🔨", scriptPath: "./items/treasure_31.js", implemented: true },
  { treasureId: "32", name: "满月", emoji: "🌕", scriptPath: "./items/treasure_32.js", implemented: true },
  { treasureId: "33", name: "向日葵", emoji: "🌻", scriptPath: "./items/treasure_33.js", implemented: true },
  { treasureId: "34", name: "木头", emoji: "🪵", scriptPath: "./items/treasure_34.js", implemented: true },
  { treasureId: "35", name: "蓝莓", emoji: "🫐", scriptPath: "./items/treasure_35.js", implemented: true },
  { treasureId: "36", name: "标签", emoji: "🏷️", scriptPath: "./items/treasure_36.js", implemented: true },
  { treasureId: "37", name: "摇杆", emoji: "🕹️", scriptPath: "./items/treasure_37.js", implemented: true },
  { treasureId: "38", name: "尺子", emoji: "📏", scriptPath: "./items/treasure_38.js", implemented: true },
  { treasureId: "39", name: "飞机", emoji: "🛫", scriptPath: "./items/treasure_39.js", implemented: true },
  { treasureId: "40", name: "书", emoji: "📖", scriptPath: "./items/treasure_40.js", implemented: true },
  { treasureId: "41", name: "蜡烛", emoji: "🕯️", scriptPath: "./items/treasure_41.js", implemented: true },
  { treasureId: "42", name: "红绿灯", emoji: "🚦", scriptPath: "./items/treasure_42.js", implemented: true },
  { treasureId: "43", name: "灯泡", emoji: "💡", scriptPath: "./items/treasure_43.js", implemented: true },
  { treasureId: "44", name: "笔记本", emoji: "📔", scriptPath: "./items/treasure_44.js", implemented: true },
  { treasureId: "45", name: "彗星", emoji: "☄️", scriptPath: "./items/treasure_45.js", implemented: true },
  { treasureId: "46", name: "证件", emoji: "🪪", scriptPath: "./items/treasure_46.js", implemented: true },
  { treasureId: "47", name: "鱼竿", emoji: "🎣", scriptPath: "./items/treasure_47.js", implemented: true },
  { treasureId: "48", name: "匕首", emoji: "🗡️", scriptPath: "./items/treasure_48.js", implemented: true },
  { treasureId: "49", name: "扫帚", emoji: "🧹", scriptPath: "./items/treasure_49.js", implemented: true },
  { treasureId: "50", name: "天平", emoji: "⚖️", scriptPath: "./items/treasure_50.js", implemented: true },
  { treasureId: "51", name: "卷轴", emoji: "📜", scriptPath: "./items/treasure_51.js", implemented: true },
  { treasureId: "52", name: "盆栽", emoji: "🪴", scriptPath: "./items/treasure_52.js", implemented: true },
  { treasureId: "53", name: "自行车", emoji: "🚲", scriptPath: "./items/treasure_53.js", implemented: true },
  { treasureId: "54", name: "火山", emoji: "🌋", scriptPath: "./items/treasure_54.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "55", name: "四叶草", emoji: "🍀", scriptPath: "./items/treasure_55.js", implemented: true },
  { treasureId: "56", name: "闪电", emoji: "⚡", scriptPath: "./items/treasure_56.js", implemented: true },
  { treasureId: "57", name: "钱袋", emoji: "💰", scriptPath: "./items/treasure_57.js", implemented: true },
  { treasureId: "58", name: "菜刀", emoji: "🔪", scriptPath: "./items/treasure_58.js", implemented: true },
  { treasureId: "59", name: "摩天轮", emoji: "🎡", scriptPath: "./items/treasure_59.js", implemented: true },
  { treasureId: "60", name: "火车", emoji: "🚂", scriptPath: "./items/treasure_60.js", implemented: true },
  { treasureId: "61", name: "星空", emoji: "🌌", scriptPath: "./items/treasure_61.js", implemented: true },
  { treasureId: "62", name: "磁铁", emoji: "🧲", scriptPath: "./items/treasure_62.js", implemented: true },
  { treasureId: "63", name: "蛇", emoji: "🐍", scriptPath: "./items/treasure_63.js", implemented: true },
  { treasureId: "64", name: "旋钮", emoji: "🎛️", scriptPath: "./items/treasure_64.js", implemented: true },
  { treasureId: "65", name: "陶罐", emoji: "🏺", scriptPath: "./items/treasure_65.js", implemented: true },
  { treasureId: "66", name: "信封", emoji: "📨", scriptPath: "./items/treasure_66.js", implemented: true },
  { treasureId: "67", name: "金牌", emoji: "🥇", scriptPath: "./items/treasure_67.js", implemented: true },
  { treasureId: "68", name: "洞", emoji: "🕳️", scriptPath: "./items/treasure_68.js", implemented: true },
  { treasureId: "69", name: "取款机", emoji: "💸", scriptPath: "./items/treasure_69.js", implemented: true },
  { treasureId: "70", name: "旗帜", emoji: "🚩", scriptPath: "./items/treasure_70.js", implemented: true },
  { treasureId: "71", name: "银行", emoji: "🏦", scriptPath: "./items/treasure_71.js", implemented: true },
  { treasureId: "72", name: "八号球", emoji: "🎱", scriptPath: "./items/treasure_72.js", implemented: true },
  { treasureId: "73", name: "手提包", emoji: "👜", scriptPath: "./items/treasure_73.js", implemented: true },
  { treasureId: "74", name: "砖块", emoji: "🧱", scriptPath: "./items/treasure_74.js", implemented: true },
  { treasureId: "78", name: "雪人", emoji: "⛄", scriptPath: "./items/treasure_78.js", implemented: true },
  { treasureId: "79", name: "棱镜", emoji: "🧿", scriptPath: "./items/treasure_79.js", implemented: true },
  { treasureId: "80", name: "泡泡", emoji: "🫧", scriptPath: "./items/treasure_80.js", implemented: true },
  { treasureId: "75", name: "计分板", emoji: "📋", scriptPath: "./items/treasure_75.js", implemented: true },
  { treasureId: "76", name: "回形针", emoji: "📎", scriptPath: "./items/treasure_76.js", implemented: true },
  { treasureId: "77", name: "彩虹", emoji: "🌈", scriptPath: "./items/treasure_77.js", implemented: true },
  { treasureId: "81", name: "培养皿", emoji: "🧫", scriptPath: "./items/treasure_81.js", implemented: true },
  { treasureId: "82", name: "蝴蝶结", emoji: "🎀", scriptPath: "./items/treasure_82.js", implemented: true },
  { treasureId: "83", name: "记事本", emoji: "📓", scriptPath: "./items/treasure_83.js", implemented: true },
  { treasureId: "84", name: "齿轮", emoji: "⚙️", scriptPath: "./items/treasure_84.js", implemented: true },
  { treasureId: "85", name: "羽毛", emoji: "🪶", scriptPath: "./items/treasure_85.js", implemented: true },
  { treasureId: "86", name: "雷管", emoji: "🧨", scriptPath: "./items/treasure_86.js", implemented: true },
  { treasureId: "87", name: "礼盒", emoji: "🎁", scriptPath: "./items/treasure_87.js", implemented: true },
  { treasureId: "88", name: "海绵", emoji: "🧽", scriptPath: "./items/treasure_88.js", implemented: true },
  { treasureId: "89", name: "邮筒", emoji: "📬", scriptPath: "./items/treasure_89.js", implemented: true },
  { treasureId: "90", name: "信用卡", emoji: "💳", scriptPath: "./items/treasure_90.js", implemented: true },
  { treasureId: "91", name: "闪星", emoji: "🌟", scriptPath: "./items/treasure_91.js", implemented: true },
  { treasureId: "92", name: "竹子", emoji: "🎋", scriptPath: "./items/treasure_92.js", implemented: true },
  { treasureId: "93", name: "小号", emoji: "🎺", scriptPath: "./items/treasure_93.js", implemented: true },
  { treasureId: "94", name: "阳光", emoji: "🔆", scriptPath: "./items/treasure_94.js", implemented: true },
  { treasureId: "95", name: "嘴", emoji: "👄", scriptPath: "./items/treasure_95.js", implemented: true },
  { treasureId: "96", name: "鬼牌", emoji: "🃏", scriptPath: "./items/treasure_96.js", implemented: true },
  { treasureId: "97", name: "滑块", emoji: "🎚️", scriptPath: "./items/treasure_97.js", implemented: true },
  { treasureId: "98", name: "面具", emoji: "🎭", scriptPath: "./items/treasure_98.js", implemented: true },
  { treasureId: "99", name: "垃圾桶", emoji: "🗑️", scriptPath: "./items/treasure_99.js", implemented: true },
  { treasureId: "100", name: "字典", emoji: "📕", scriptPath: "./items/treasure_100.js", implemented: true },
  { treasureId: "101", name: "蜡笔", emoji: "🖍️", scriptPath: "./items/treasure_101.js", implemented: true },
  { treasureId: "102", name: "跑步", emoji: "🏃", scriptPath: "./items/treasure_102.js", implemented: true },
  { treasureId: "103", name: "剪刀", emoji: "✂️", scriptPath: "./items/treasure_103.js", implemented: true },
  { treasureId: "104", name: "镜子", emoji: "🪞", scriptPath: "./items/treasure_104.js", implemented: true },
  { treasureId: "105", name: "绵羊", emoji: "🐑", scriptPath: "./items/treasure_105.js", implemented: true },
  { treasureId: "106", name: "工具", emoji: "🛠️", scriptPath: "./items/treasure_106.js", implemented: true },
  { treasureId: "107", name: "钢琴", emoji: "🎹", scriptPath: "./items/treasure_107.js", implemented: true },
  { treasureId: "108", name: "书包", emoji: "🎒", scriptPath: "./items/treasure_108.js", implemented: true },
  { treasureId: "109", name: "魔杖", emoji: "🪄", scriptPath: "./items/treasure_109.js", implemented: true },
  { treasureId: "110", name: "门票", emoji: "🎟️", scriptPath: "./items/treasure_110.js", implemented: true },
  { treasureId: "111", name: "日历", emoji: "📆", scriptPath: "./items/treasure_111.js", implemented: true },
  { treasureId: "112", name: "钞票", emoji: "💵", scriptPath: "./items/treasure_112.js", implemented: true },
  { treasureId: "113", name: "花环", emoji: "🏵️", scriptPath: "./items/treasure_113.js", implemented: true },
  { treasureId: "114", name: "棋子", emoji: "♟️", scriptPath: "./items/treasure_114.js", implemented: true },
  { treasureId: "115", name: "洗衣篮", emoji: "🧺", scriptPath: "./items/treasure_115.js", implemented: true },
  { treasureId: "116", name: "盾牌", emoji: "🛡️", scriptPath: "./items/treasure_116.js", implemented: true },
  { treasureId: "117", name: "光盘", emoji: "💿", scriptPath: "./items/treasure_117.js", implemented: true },
  { treasureId: "118", name: "寻呼机", emoji: "📟", scriptPath: "./items/treasure_118.js", implemented: true },
  {
    treasureId: "119",
    name: "风筝",
    emoji: "🪁",
    scriptPath: "./items/treasure_119.js",
    implemented: true,
    collectionOrder: 0,
    introducedVersion: "1.0.1",
  },
  {
    treasureId: "120",
    name: "手枪",
    emoji: "🔫",
    scriptPath: "./items/treasure_120.js",
    implemented: true,
    introducedVersion: "1.1.0",
  },
  { treasureId: "121", name: "红包", emoji: "🧧", scriptPath: "./items/treasure_121.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "122", name: "梯子", emoji: "🪜", scriptPath: "./items/treasure_122.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "123", name: "水桶", emoji: "🪣", scriptPath: "./items/treasure_123.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "124", name: "账本", emoji: "📒", scriptPath: "./items/treasure_124.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "125", name: "茶壶", emoji: "🫖", scriptPath: "./items/treasure_125.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "126", name: "灯笼", emoji: "🏮", scriptPath: "./items/treasure_126.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "127", name: "螺栓", emoji: "🔩", scriptPath: "./items/treasure_127.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "128", name: "老虎机", emoji: "🎰", scriptPath: "./items/treasure_128.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "129", name: "烟花", emoji: "🎆", scriptPath: "./items/treasure_129.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "130", name: "蜂蜜", emoji: "🍯", scriptPath: "./items/treasure_130.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "131", name: "橙子", emoji: "🍊", scriptPath: "./items/treasure_131.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "132", name: "存钱罐", emoji: "🐷", scriptPath: "./items/treasure_132.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "133", name: "购物车", emoji: "🛒", scriptPath: "./items/treasure_133.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "134", name: "电视机", emoji: "📺", scriptPath: "./items/treasure_134.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "135", name: "行李箱", emoji: "🧳", scriptPath: "./items/treasure_135.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "136", name: "钥匙", emoji: "🗝️", scriptPath: "./items/treasure_136.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "137", name: "电池", emoji: "🔋", scriptPath: "./items/treasure_137.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "138", name: "奖杯", emoji: "🏆", scriptPath: "./items/treasure_138.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "139", name: "传真机", emoji: "📠", scriptPath: "./items/treasure_139.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "140", name: "报纸", emoji: "🗞️", scriptPath: "./items/treasure_140.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "141", name: "购物袋", emoji: "🛍️", scriptPath: "./items/treasure_141.js", implemented: true, introducedVersion: "1.2.0" },
  { treasureId: "142", name: "流星", emoji: "🌠", scriptPath: "./items/treasure_142.js", implemented: true, introducedVersion: "1.2.0" },
];

export const TREASURE_CATALOG_BY_ID = new Map(TREASURE_CATALOG.map((t) => [t.treasureId, t]));

/** @param {string | null | undefined} treasureId */
export function resolveTreasureIntroducedVersion(treasureId) {
  const entry = TREASURE_CATALOG_BY_ID.get(String(treasureId ?? "").trim());
  return entry?.introducedVersion ?? DEFAULT_TREASURE_INTRODUCED_VERSION;
}
export const IMPLEMENTED_TREASURE_ID_SET = new Set(
  TREASURE_CATALOG.filter((t) => t.implemented).map((t) => t.treasureId),
);
