/** 宝藏展示、脚本路径与实现状态目录（集中维护） */
export const TREASURE_CATALOG = [
  { treasureId: "1", name: "火花", emoji: "✨", scriptPath: "./items/treasure_1.js", implemented: true },
  { treasureId: "2", name: "铅笔", emoji: "✏️", scriptPath: "./items/treasure_2.js", implemented: true },
  { treasureId: "3", name: "宝石", emoji: "💎", scriptPath: "./items/treasure_3.js", implemented: true },
  { treasureId: "4", name: "水晶球", emoji: "🔮", scriptPath: "./items/treasure_4.js", implemented: true },
  { treasureId: "5", name: "王冠", emoji: "👑", scriptPath: "./items/treasure_5.js", implemented: true },
  { treasureId: "6", name: "链条", emoji: "⛓️", scriptPath: "./items/treasure_6.js", implemented: true },
  { treasureId: "7", name: "扩音器", emoji: "📢", scriptPath: "./items/treasure_7.js", implemented: true },
  { treasureId: "8", name: "放大镜", emoji: "🔍", scriptPath: "./items/treasure_8.js", implemented: true },
  { treasureId: "9", name: "拼图", emoji: "🧩", scriptPath: "./items/treasure_9.js", implemented: true },
  { treasureId: "10", name: "名牌", emoji: "📛", scriptPath: "./items/treasure_10.js", implemented: true },
  { treasureId: "11", name: "键盘", emoji: "⌨️", scriptPath: "./items/treasure_11.js", implemented: true },
  { treasureId: "12", name: "碗", emoji: "🥣", scriptPath: "./items/treasure_12.js", implemented: true },
  { treasureId: "13", name: "雪花", emoji: "❄️", scriptPath: "./items/treasure_13.js", implemented: true },
  { treasureId: "14", name: "调色盘", emoji: "🎨", scriptPath: "./items/treasure_14.js", implemented: true },
  { treasureId: "15", name: "丝带", emoji: "🎗️", scriptPath: "./items/treasure_15.js", implemented: true },
  { treasureId: "16", name: "沙漏", emoji: "⌛", scriptPath: "./items/treasure_16.js", implemented: true },
  { treasureId: "17", name: "椅子", emoji: "🪑", scriptPath: "./items/treasure_17.js", implemented: true },
  { treasureId: "18", name: "手包", emoji: "👝", scriptPath: "./items/treasure_18.js", implemented: true },
  { treasureId: "19", name: "火", emoji: "🔥", scriptPath: "./items/treasure_19.js", implemented: true },
  { treasureId: "20", name: "篮球", emoji: "🏀", scriptPath: "./items/treasure_20.js", implemented: true },
  { treasureId: "21", name: "骰子", emoji: "🎲", scriptPath: "./items/treasure_21.js", implemented: true },
  { treasureId: "22", name: "号角", emoji: "📯", scriptPath: "./items/treasure_22.js", implemented: true },
  { treasureId: "23", name: "望远镜", emoji: "🔭", scriptPath: "./items/treasure_23.js", implemented: false },
  { treasureId: "24", name: "小票", emoji: "🧾", scriptPath: "./items/treasure_24.js", implemented: false },
  { treasureId: "25", name: "备忘录", emoji: "📝", scriptPath: "./items/treasure_25.js", implemented: true },
  { treasureId: "26", name: "书本", emoji: "📚", scriptPath: "./items/treasure_26.js", implemented: true },
  { treasureId: "27", name: "硬币", emoji: "🪙", scriptPath: "./items/treasure_27.js", implemented: false },
  { treasureId: "28", name: "乐谱", emoji: "🎼", scriptPath: "./items/treasure_28.js", implemented: false },
  { treasureId: "29", name: "电池", emoji: "🔋", scriptPath: "./items/treasure_29.js", implemented: true },
  { treasureId: "30", name: "试管", emoji: "🧪", scriptPath: "./items/treasure_30.js", implemented: true },
  { treasureId: "31", name: "锤子", emoji: "🔨", scriptPath: "./items/treasure_31.js", implemented: true },
  { treasureId: "32", name: "满月", emoji: "🌕", scriptPath: "./items/treasure_32.js", implemented: true },
  { treasureId: "33", name: "黄圆点", emoji: "🟡", scriptPath: "./items/treasure_33.js", implemented: true },
  { treasureId: "34", name: "木头", emoji: "🪵", scriptPath: "./items/treasure_34.js", implemented: true },
  { treasureId: "35", name: "蓝钻", emoji: "🔷", scriptPath: "./items/treasure_35.js", implemented: true },
  { treasureId: "36", name: "标签", emoji: "🏷️", scriptPath: "./items/treasure_36.js", implemented: true },
  { treasureId: "37", name: "摇杆", emoji: "🕹️", scriptPath: "./items/treasure_37.js", implemented: false },
  { treasureId: "38", name: "尺子", emoji: "📏", scriptPath: "./items/treasure_38.js", implemented: true },
  { treasureId: "39", name: "飞机", emoji: "🛫", scriptPath: "./items/treasure_39.js", implemented: false },
  { treasureId: "40", name: "书", emoji: "📖", scriptPath: "./items/treasure_40.js", implemented: false },
  { treasureId: "41", name: "封蜡", emoji: "🕯️", scriptPath: "./items/treasure_41.js", implemented: false },
  { treasureId: "42", name: "红绿灯", emoji: "🚦", scriptPath: "./items/treasure_42.js", implemented: false },
  { treasureId: "43", name: "灯泡", emoji: "💡", scriptPath: "./items/treasure_43.js", implemented: false },
  { treasureId: "44", name: "笔记本", emoji: "📔", scriptPath: "./items/treasure_44.js", implemented: false },
  { treasureId: "45", name: "打印机", emoji: "🖨️", scriptPath: "./items/treasure_45.js", implemented: false },
  { treasureId: "46", name: "证件", emoji: "🪪", scriptPath: "./items/treasure_46.js", implemented: false },
  { treasureId: "47", name: "算盘", emoji: "🧮", scriptPath: "./items/treasure_47.js", implemented: true },
  { treasureId: "48", name: "匕首", emoji: "🗡️", scriptPath: "./items/treasure_48.js", implemented: false },
  { treasureId: "49", name: "闪电", emoji: "⚡", scriptPath: false, implemented: false },
  { treasureId: "50", name: "砖块", emoji: "🧱", scriptPath: false, implemented: false },
  { treasureId: "51", name: "扫帚", emoji: "🧹", scriptPath: false, implemented: false },
  { treasureId: "52", name: "天平", emoji: "⚖️", scriptPath: false, implemented: false },
  { treasureId: "53", name: "银行卡", emoji: "💳", scriptPath: false, implemented: false },
  { treasureId: "54", name: "炸弹", emoji: "💣", scriptPath: false, implemented: false },
  { treasureId: "55", name: "箱子", emoji: "📦", scriptPath: false, implemented: false },
  { treasureId: "56", name: "卷轴", emoji: "📜", scriptPath: false, implemented: false },
  { treasureId: "57", name: "紫方块", emoji: "🟪", scriptPath: false, implemented: false },
  { treasureId: "58", name: "工具箱", emoji: "🧰", scriptPath: false, implemented: false },
  { treasureId: "59", name: "面具", emoji: "🎭", scriptPath: false, implemented: false },
  { treasureId: "60", name: "火车", emoji: "🚂", scriptPath: false, implemented: false },
  { treasureId: "61", name: "星空", emoji: "🌌", scriptPath: false, implemented: false },
  { treasureId: "62", name: "磁铁", emoji: "🧲", scriptPath: false, implemented: false },
  { treasureId: "63", name: "钱袋", emoji: "💰", scriptPath: false, implemented: false },
  { treasureId: "64", name: "旋钮", emoji: "🎛️", scriptPath: false, implemented: false },
  { treasureId: "65", name: "陶罐", emoji: "🏺", scriptPath: false, implemented: false },
  { treasureId: "66", name: "信封", emoji: "📨", scriptPath: false, implemented: false },
  { treasureId: "67", name: "金牌", emoji: "🥇", scriptPath: false, implemented: false },
  { treasureId: "68", name: "上涨图", emoji: "📈", scriptPath: false, implemented: false },
  { treasureId: "69", name: "洞", emoji: "🕳️", scriptPath: false, implemented: false },
  { treasureId: "70", name: "取款机", emoji: "🏧", scriptPath: false, implemented: false },
  { treasureId: "71", name: "A键", emoji: "🅰️", scriptPath: false, implemented: false },
  { treasureId: "72", name: "银行", emoji: "🏦", scriptPath: false, implemented: false },
  { treasureId: "73", name: "加号", emoji: "➕", scriptPath: false, implemented: false },
  { treasureId: "74", name: "手提包", emoji: "👜", scriptPath: false, implemented: false },
  { treasureId: "75", name: "剪贴板", emoji: "📋", scriptPath: "./items/treasure_75.js", implemented: true },
  { treasureId: "76", name: "回形针", emoji: "📎", scriptPath: "./items/treasure_76.js", implemented: true },
  { treasureId: "77", name: "彩虹", emoji: "🌈", scriptPath: "./items/treasure_77.js", implemented: true },
];

export const TREASURE_CATALOG_BY_ID = new Map(TREASURE_CATALOG.map((t) => [t.treasureId, t]));
export const IMPLEMENTED_TREASURE_ID_SET = new Set(
  TREASURE_CATALOG.filter((t) => t.implemented).map((t) => t.treasureId),
);
